eureka:
  instance:
    hostname: helppoint_discovery_server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://helppoint_discovery_server:8761/eureka/